### PR TITLE
Add info about how to test page caching in development environment.

### PR DESCRIPTION
**Pull request by mechanicles**

### CODE REVIEW

**Comment by mechanicles** [comment]
@rafaelfranca How about this doc info?

**Comment by nathanstitt** [comment]
I just stumbled on this while attempting to figure out how to best test caching in development.

While the info here's good, you'll also have to turn on `perform_caching` in the development environment by adding the below to the `config/environments/development.rb` file:
```
config.action_controller.perform_caching = true
```

**Comment by fxn** [comment]
Since Rails 5, the idiomatic way to do this is to execute the toggler

```
bin/rails dev:cache
```

I have done a complete revision of the README in 22d65071e999a07d35a9c9ce7b14bd5ac227f100 and has covered this among other things.

Thanks for bringing our attention to this, and for volunteering a patch ❤️.

**Pull request closed without merging**
